version : '3'

services:
    lb:
        image: haproxy
        ports:
            - "8080:8080"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    nodeapp1:
        image: nodeapp
        environment:
            - APPID=1111
            - DATABASE=mongodb://127.0.0.1:27017
    nodeapp2:
        image: nodeapp
        environment:
            - APPID=2222
            - DATABASE=mongodb://127.0.0.1:27018
    nodeapp3:
        image: nodeapp
        environment:
            - APPID=3333
            - DATABASE=mongodb://127.0.0.1:27018
    nodeapp4:
        image: nodeapp
        environment:
            - APPID=4444
            - DATABASE=mongodb://127.0.0.1:27018
    nodeapp5:
        image: nodeapp
        environment:
            - APPID=5555
            - DATABASE=mongodb://127.0.0.1:27018

    
        